# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days Summer 2022'
tagline:          'Packages and Matrix Objects'
description:      '17<sup>th</sup> to 21<sup>st</sup> October 2022'
location:         'RWTH Aachen University'
url:              https://www.gapdays.de
baseurl:          /gapdays2022-summer


exclude: [ "LICENSE.hyde.md", "README.hyde.md", "program.aux", "program.log", "program.out", "program.tex", "misc" ]
